---
cache_dir: /home/stock/data/Documents/Projects/the_matrix/cache/
mssql:
  server: 0.0.0.0
  instance: xxxxxx
  username: xxxxxx
  password: xxxxxx
  cache_dir: /home/stock/nvme/project-fusion/cache/
logs:
  default:
    log_path: "."
    log_opencl: true
    log_to: Console
    level: Trace
    levels:
      - module: tokio_tungstenite
        level: Info
      - module: tungstenite
        level: Info
      - module: hyper
        level: Info
      - module: want
        level: Info
      - module: mio
        level: Info
      - module: tracing
        level: Info
      - module: azure_storage
        level: Info
      - module: rustls
        level: Info
    level_colors:
      error: Red
      warn: Yellow
      info: Green
      debug: White
      trace: BrightBlack
