# Unstable features below
unstable_features = true
version = "Two"

# when doing cargo fix set imports_granularity to module then `cargo fix`
imports_granularity = "Crate"
# after cargo fix there will be blank lines where imports used to be, this removes them
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
format_strings = true
normalize_comments = true
empty_item_single_line = true
format_macro_matchers = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
